### PR TITLE
Vendor Improvements

### PR DESCRIPTION
**Pull request by techno-sam**
- Toggle button to enable/disable item extraction from vendors
- Bulk buy/sell up to a stack of items to vendors by sneaking while using the vendor
- The buying/selling item slot in the vendor gui now acts like a ghost item (does not require actual items).
  Backwards compatible with existing vendors, so the items will remain 'real' until you remove them.
  Additionally, enchantments and dyes can be applied to some items by shift-dragging items when using EMI on fabric or JEI on forge

### CODE REVIEW

**Comment by techno-sam** [comment]
resolves #93

**Comment by techno-sam** [comment]
closes #93

**Comment by techno-sam** [comment]
closes #84

**Comment by techno-sam** [comment]
closes #57

**Review by IThundxr — APPROVED** [review]

**Pull request merged**
